"""Export S2: metric-sensitivity sweep in a wide, human-readable form.

Reads results/sensitivity.csv (long-format: one row per model×descriptor,
carrying baseline / min / max across the three per-state rescalings) and
writes two artefacts:

    supp/S2_sensitivity.csv   twelve rows, per-descriptor columns for
                              baseline / min / max — the version to cite.
    supp/S2_sensitivity.md    the same table rendered as markdown for
                              the supplementary PDF.
"""
from __future__ import annotations

import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "results" / "sensitivity.csv"
OUT_CSV = ROOT / "supp" / "S2_sensitivity.csv"
OUT_MD  = ROOT / "supp" / "S2_sensitivity.md"

DISPLAY = {
    "tcr":               "TCR proofreading",
    "predator_prey":     "Neubert–Caswell predator–prey",
    "murphy_miller":     "Murphy–Miller balanced E–I",
    "selkov":            "Selkov glycolysis",
    "nfkb":              "NF-κB / IκB",
    "repressilator_het": "Repressilator (heterogeneous)",
    "repressilator":     "Repressilator (symmetric)",
    "goodwin":           "Goodwin",
    "toggle":            "Toggle (symmetric)",
    "toggle_het":        "Toggle (heterogeneous)",
    "relay":             "Relay (symmetric)",
    "relay_het":         "Relay (heterogeneous)",
}
ORDER = list(DISPLAY)                # panel order matches Fig 2a
DESCRIPTORS = ["nu", "omega", "G_max"]


def load():
    by_model = {}
    with SRC.open() as f:
        for r in csv.DictReader(f):
            by_model.setdefault(r["model"], {})[r["descriptor"]] = (
                float(r["baseline"]),
                float(r["min_over_scalings"]),
                float(r["max_over_scalings"]),
            )
    return by_model


def write_csv(rows):
    header = ["model", "display_name"]
    for d in DESCRIPTORS:
        for suffix in ("baseline", "min", "max"):
            header.append(f"{d}_{suffix}")
    with OUT_CSV.open("w", newline="") as f:
        w = csv.writer(f)
        w.writerow(header)
        for key in ORDER:
            r = rows[key]
            row = [key, DISPLAY[key]]
            for d in DESCRIPTORS:
                b, lo, hi = r[d]
                row.extend([f"{b:.4f}", f"{lo:.4f}", f"{hi:.4f}"])
            w.writerow(row)


def fmt(v):
    return f"{v:+.3f}" if abs(v) < 1000 else f"{v:.2e}"


def write_md(rows):
    lines = []
    lines.append("# Supplementary Table S2 — Metric-sensitivity sweep")
    lines.append("")
    lines.append(
        "**Protocol.** Every twelve-computation entry is re-evaluated under "
        "three per-state rescalings of the Jacobian: uniform ×0.5, uniform "
        "×2.0, and a per-state draw from Uniform(0.5, 2.0) with a fixed seed "
        "(numpy.random.default_rng(0)). Baseline is the descriptor at the "
        "stated operating point; min / max span the values across the three "
        "rescalings."
    )
    lines.append("")
    lines.append(
        "**Reading.** Q is invariant under change of representation and is "
        "not tabulated. ν, ω and G_max are metric-relative. Two systems "
        "have ω crossing zero under some rescaling (symmetric repressilator, "
        "Goodwin) — these are the two amber points in Figure 2a. NF-κB "
        "sits close to the zero boundary at ω = +0.009 but does not cross "
        "(minimum +0.001). Selkov's ω stays positive throughout (min +0.294)."
    )
    lines.append("")

    # header
    lines.append(
        "| Model | ν baseline | ν min | ν max | ω baseline | ω min | ω max | "
        "G_max baseline | G_max min | G_max max |"
    )
    lines.append(
        "|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|"
    )

    for key in ORDER:
        r = rows[key]
        nu_b, nu_lo, nu_hi = r["nu"]
        om_b, om_lo, om_hi = r["omega"]
        g_b,  g_lo,  g_hi  = r["G_max"]
        lines.append(
            f"| {DISPLAY[key]} "
            f"| {nu_b:.3f} | {nu_lo:.3f} | {nu_hi:.3f} "
            f"| {fmt(om_b)} | {fmt(om_lo)} | {fmt(om_hi)} "
            f"| {g_b:.3f} | {g_lo:.3f} | {g_hi:.3f} |"
        )

    lines.append("")
    lines.append("Source: `results/sensitivity.csv`, generated by `sweep.py`.")
    lines.append("")
    OUT_MD.write_text("\n".join(lines))


def main():
    rows = load()
    write_csv(rows)
    write_md(rows)
    print(f"wrote {OUT_CSV.relative_to(ROOT)}")
    print(f"wrote {OUT_MD.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
